### PR TITLE
Complete error list as of MySQL 8.0.19

### PR DESCRIPTION
**Pull request by pmatseykanets**
Regenerate the complete error list as of MySQL 8.0.19.

### CODE REVIEW

**Review by efepapa — APPROVED** [review]

**Review by gkristic-vc — APPROVED** [review]
No reasonable way for me to review this, other than building it up from scratch and comparing, so... approved :D

**Review by efepapa — APPROVED** [review]

**Comment by pmatseykanets** [comment]
For completeness:

- regenerated the whole file and included new symbol names for all constants in inline comments for reference
- updated the copyright in the LICENSE file
- set up a simple GitHub Action workflow that makes sure there were no syntax errors introduced

**Review by efepapa — APPROVED** [review]

**Comment by jeffwidman** [comment]
One question--is there any additional errors or difference in codes used by MariaDB compared to MySQL? I'm guessing not, but wanted to doublecheck... if so, then perhaps those should also be available through this pkg, but as a different file.

**Comment by pmatseykanets** [comment]
> is there any additional errors or difference in codes used by MariaDB compared to MySQL?

AFAIK there are no immediate plans to support MariaDB error codes even if there are differences.

**Pull request merged**
